name: CI
on:
  pull_request:
    paths:
      - "terraform/**.tf"
      - "wordpress/**"
      - ".github/workflows/ci.yml"

concurrency: ci-${{ github.ref }}

jobs:
  wordpress:
    name: wordpress
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      AWS_REGION: eu-west-1
      BUCKET_URL: s3://interviewuser1-app-bucket20220420101811790700000001/

    defaults:
      run:
        working-directory: wordpress

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Zip & Deploy Wordpress Code
        run: |
          tar -cfR wordpress.tar *
          gzip wordpress.tar
          aws s3 cp wordpress.tar.gz $BUCKET_URL --dry-run

  terraform:
    name: terraform plan
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      AWS_REGION: eu-west-1

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: hashicorp/setup-terraform@v1
      - name: format check
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: terraform init
        id: init
        run: terraform init
      - name: terraform plan
        id: plan
        run: terraform plan